# Generated by Django 5.1.3 on 2024-11-26 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_notelist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notelist',
            options={'verbose_name': 'Список заметок', 'verbose_name_plural': 'Списки заметок'},
        ),
    ]
