# Generated by Django 5.1.3 on 2024-11-26 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_alter_customer_expires_in_and_more'),
        ('notes', '0003_alter_notelist_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notelist',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer', verbose_name='Пользователь'),
        ),
    ]
