# Generated by Django 5.1 on 2024-09-20 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_alter_subject_options_question_subject_test_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='weight',
            field=models.PositiveIntegerField(default=1, verbose_name='Вес вопроса'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='questions.question', verbose_name='Вопрос'),
        ),
    ]
