# Generated by Django 5.1 on 2024-10-25 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_alter_customer_email_alter_customer_first_name_and_more'),
        ('questions', '0003_question_weight_alter_answer_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('attempt_number', models.IntegerField(default=1, verbose_name='Номер попытки')),
                ('end_time', models.DateTimeField(null=True, verbose_name='Конец выполнения теста')),
                ('user_answers', models.JSONField(verbose_name='Ответы пользователя')),
                ('total_score', models.IntegerField(null=True, verbose_name='Баллы')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.test', verbose_name='Тест')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Попытка',
                'verbose_name_plural': 'Попытки',
            },
        ),
    ]
