# Generated by Django 5.1.2 on 2024-10-29 17:00

import core.apps.customers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_alter_customer_email_alter_customer_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='expires_in',
            field=models.BigIntegerField(default=core.apps.customers.models.Customer.get_expires_in, verbose_name='Время до истечения access token'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='refresh_expires_in',
            field=models.BigIntegerField(default=core.apps.customers.models.Customer.get_refresh_expires_in, verbose_name='Время до истечения refresh token'),
        ),
    ]
